name: Create Azure Storage via Issue
title: "Create Storage - "
description: Form to create Azure storage + GitHub repo automatically
labels: ["storage-auto"]
body:
  - type: input
    id: storage_name
    attributes:
      label: Storage Account Name
    validations:
      required: true

  - type: input
    id: resource_group
    attributes:
      label: Resource Group Name
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Azure Location
      value: canadacentral
    validations:
      required: true

  - type: input
    id: azure_client_id
    attributes:
      label: Azure Client ID
    validations:
      required: true

  - type: input
    id: azure_tenant_id
    attributes:
      label: Azure Tenant ID
    validations:
      required: true

  - type: input
    id: azure_subscription_id
    attributes:
      label: Azure Subscription ID
    validations:
      required: true

  - type: input
    id: github_account
    attributes:
      label: GitHub Account Name
    validations:
      required: true

  - type: input
    id: github_token
    attributes:
      label: GitHub Token (PAT)
    validations:
      required: true

  - type: input
    id: repo_name
    attributes:
      label: Output Repo Name
    validations:
      required: true
